# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3307/course_management?createDatabaseIfNotExist=true
#     username: root
#     password: root123
#     driver-class-name: com.mysql.cj.jdbc.Driver
  
#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true
#     properties:
#       hibernate:
#         format_sql: true
#         dialect: org.hibernate.dialect.MySQL8Dialect

# server:
#   port: 8080

spring:
  application:
    name: course-management
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3307/course_management?createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root123}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: ${JWT_EXPIRATION:86400000}

logging:
  level:
    com.university.coursemanagement: ${LOG_LEVEL:DEBUG}