package com.university.course_managment.dto;

import java.util.List;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class StudentDTO {
    private Long id;
    private String studentId;
    private String firstName;
    private String lastName;
    private String email;
    private String department;
    private Integer year;
    private Long userId;
    private List<CourseDTO> courses;
    
    // Add this field that was missing
    private Integer enrolledCourses;
    
    // Getter and setter methods will be generated by Lombok @Data annotation
    public Long getUserId() {
        return userId;
    }
    
    public void setUserId(Long userId) {
        this.userId = userId;
    }
    
    public Integer getEnrolledCourses() {
        return enrolledCourses;
    }
    
    public void setEnrolledCourses(Integer enrolledCourses) {
        this.enrolledCourses = enrolledCourses;
    }
}